/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uni.aed.gui;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import uni.aed.Comparator.IntegerComparator;
import uni.aed.directorio.DirectorioV1;
import uni.aed.model.Persona;
import uni.aed.directorio.Directorio;
import uni.aed.ordenamiento.SortObject;

/**
 *
 * @author mitch
 */
public class FrmDirectory extends javax.swing.JFrame {

    private final DefaultListModel modelListInitial = new DefaultListModel();
    private final DefaultListModel modelListFinal = new DefaultListModel();
    private final String CADENA_VACIA = "";
    private Directorio dir;
    ImageIcon batman;
    
    public FrmDirectory() {
        initComponents();
        dir = new DirectorioV1();
        lstInitial.setModel(modelListInitial);
        lstFinal.setModel(modelListFinal);
        txtName.requestFocus();
        batman = new ImageIcon("C:\\Users\\mitch\\OneDrive\\Documentos\\NetBeansProjects\\SortProject\\src\\main\\java\\uni\\aed\\icons\\iconBatman.png");
        panelDataIntegerEntry(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlDataPersonEntry = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        cboxGender = new javax.swing.JComboBox<>();
        jpnlOperations = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jpnlCriterios = new javax.swing.JPanel();
        rbtnName = new javax.swing.JRadioButton();
        rbtnAge = new javax.swing.JRadioButton();
        cboxAlgorithm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSort = new javax.swing.JButton();
        jpnlLista1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstInitial = new javax.swing.JList<>();
        jpnlLista2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFinal = new javax.swing.JList<>();
        cboxTypeSorting = new javax.swing.JComboBox<>();
        jpnlDataIntegerEntry = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIntegerValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel2.setText("Age");

        jLabel3.setText("Gender");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        cboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non Binarie" }));
        cboxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxGenderActionPerformed(evt);
            }
        });
        cboxGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxGenderKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpnlDataPersonEntryLayout = new javax.swing.GroupLayout(jpnlDataPersonEntry);
        jpnlDataPersonEntry.setLayout(jpnlDataPersonEntryLayout);
        jpnlDataPersonEntryLayout.setHorizontalGroup(
            jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDataPersonEntryLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDataPersonEntryLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlDataPersonEntryLayout.createSequentialGroup()
                        .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge)
                            .addComponent(cboxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpnlDataPersonEntryLayout.setVerticalGroup(
            jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDataPersonEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpnlDataPersonEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        btnRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegisterKeyPressed(evt);
            }
        });

        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnClose.setText("Close");

        javax.swing.GroupLayout jpnlOperationsLayout = new javax.swing.GroupLayout(jpnlOperations);
        jpnlOperations.setLayout(jpnlOperationsLayout);
        jpnlOperationsLayout.setHorizontalGroup(
            jpnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlOperationsLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jpnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegister)
                    .addComponent(btnClean)
                    .addComponent(btnClose))
                .addGap(38, 38, 38))
        );
        jpnlOperationsLayout.setVerticalGroup(
            jpnlOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOperationsLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnClean)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(26, 26, 26))
        );

        jpnlCriterios.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorting criteria"));

        rbtnName.setSelected(true);
        rbtnName.setText("Name");
        rbtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNameActionPerformed(evt);
            }
        });

        rbtnAge.setText("Age");
        rbtnAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAgeActionPerformed(evt);
            }
        });

        cboxAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HeapSort" }));

        jLabel4.setText("Sorting algorithm");

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlCriteriosLayout = new javax.swing.GroupLayout(jpnlCriterios);
        jpnlCriterios.setLayout(jpnlCriteriosLayout);
        jpnlCriteriosLayout.setHorizontalGroup(
            jpnlCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCriteriosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(rbtnName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSort)
                .addGap(70, 70, 70))
        );
        jpnlCriteriosLayout.setVerticalGroup(
            jpnlCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCriteriosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnlCriteriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnName)
                    .addComponent(rbtnAge)
                    .addComponent(jLabel4)
                    .addComponent(cboxAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSort))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(lstInitial);

        javax.swing.GroupLayout jpnlLista1Layout = new javax.swing.GroupLayout(jpnlLista1);
        jpnlLista1.setLayout(jpnlLista1Layout);
        jpnlLista1Layout.setHorizontalGroup(
            jpnlLista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlLista1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jpnlLista1Layout.setVerticalGroup(
            jpnlLista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlLista1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(lstFinal);

        javax.swing.GroupLayout jpnlLista2Layout = new javax.swing.GroupLayout(jpnlLista2);
        jpnlLista2.setLayout(jpnlLista2Layout);
        jpnlLista2Layout.setHorizontalGroup(
            jpnlLista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlLista2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jpnlLista2Layout.setVerticalGroup(
            jpnlLista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlLista2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        cboxTypeSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personas", "Integers" }));
        cboxTypeSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTypeSortingActionPerformed(evt);
            }
        });

        jLabel5.setText("Enteros");

        txtIntegerValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntegerValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlDataIntegerEntryLayout = new javax.swing.GroupLayout(jpnlDataIntegerEntry);
        jpnlDataIntegerEntry.setLayout(jpnlDataIntegerEntryLayout);
        jpnlDataIntegerEntryLayout.setHorizontalGroup(
            jpnlDataIntegerEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDataIntegerEntryLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(txtIntegerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jpnlDataIntegerEntryLayout.setVerticalGroup(
            jpnlDataIntegerEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDataIntegerEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDataIntegerEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIntegerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnlDataIntegerEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpnlDataPersonEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jpnlOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(cboxTypeSorting, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpnlLista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jpnlLista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpnlCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlDataIntegerEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jpnlDataPersonEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxTypeSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jpnlOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jpnlCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlLista2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlLista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        try{
            Integer edad = Integer.parseInt(txtAge.getText());
        }catch(NumberFormatException ivan){
            JOptionPane.showMessageDialog(this, "Escribe bien kbro", "Kbrazo", JOptionPane.ERROR_MESSAGE, batman);
            txtAge.requestFocus();
            txtAge.selectAll();
        }
        
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        register();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void register() {
        
        if (cboxTypeSorting.getSelectedIndex() == 0) {
           String name = txtName.getText();
            int age = Integer.parseInt(txtAge.getText());
            if (age < 14 || age > 99) {
                JOptionPane.showMessageDialog(this, "Ingrese una edad entre [14, 99]", "Edad incorrecta", ERROR);
                return;
            }

            String gender = (String)cboxGender.getSelectedItem();
            Persona persona = new Persona(name, age, gender.charAt(0));

            dir.add(persona);
            modelListInitial.addElement(persona.toString());
            clearEntry();
            txtName.requestFocus(); 
        }
        else {
            Integer value = Integer.parseInt(txtIntegerValue.getText());
            modelListInitial.addElement(value);
            txtIntegerValue.setText(CADENA_VACIA);
            txtIntegerValue.requestFocus();
                    
        }
        
        
        
        
    }
    
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtAge.requestFocus();
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
            
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            cboxGender.requestFocus();
    }//GEN-LAST:event_txtAgeKeyPressed

    private void cboxGenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxGenderKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnRegister.requestFocus();
    }//GEN-LAST:event_cboxGenderKeyPressed

    private void btnRegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegisterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_btnRegisterKeyPressed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        Persona [] sortedList;
        
        if(cboxTypeSorting.getSelectedIndex() == 0) {
            
        }
        else {
            IntegerComparator comp = new IntegerComparator();
            Object [] list = modelListInitial.toArray();
            SortObject sort = new SortObject(comp);
            Object [] sorted = sort.HeapSort(list);
            for(Object e : sorted)
                modelListFinal.addElement(e);
    
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void rbtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNameActionPerformed
        rbtnAge.setSelected(false);
    }//GEN-LAST:event_rbtnNameActionPerformed

    private void rbtnAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAgeActionPerformed
        rbtnName.setSelected(false);
    }//GEN-LAST:event_rbtnAgeActionPerformed

    private void cboxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxGenderActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanActionPerformed

    private void cboxTypeSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTypeSortingActionPerformed
        if(cboxTypeSorting.getSelectedIndex() == 0){
            panelDataIntegerEntry(false);
            panelDataPersonEntry(true);
        }else{
            panelDataPersonEntry(false);
            panelDataIntegerEntry(true);
        }
    }//GEN-LAST:event_cboxTypeSortingActionPerformed

    private void txtIntegerValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntegerValueActionPerformed
        register();
    }//GEN-LAST:event_txtIntegerValueActionPerformed
    
    private void panelDataIntegerEntry(boolean b) {
        
        txtIntegerValue.setEditable(b);     
    }
    
    private void panelDataPersonEntry(boolean b) {
        
        txtName.setEditable(b);
        txtAge.setEditable(b);
        cboxGender.setEnabled(b);
        rbtnAge.setEnabled(b);
        rbtnAge.setVisible(b);
        rbtnName.setEnabled(b);
        rbtnName.setVisible(b);
        btnRegister.setEnabled(b);
        btnClean.setEnabled(b);
        btnClose.setEnabled(b);
        
    }
    
    private void clearEntry() {
        txtName.setText(CADENA_VACIA);
        txtAge.setText(CADENA_VACIA);
        cboxGender.setSelectedIndex(0);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDirectory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDirectory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSort;
    private javax.swing.JComboBox<String> cboxAlgorithm;
    private javax.swing.JComboBox<String> cboxGender;
    private javax.swing.JComboBox<String> cboxTypeSorting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnlCriterios;
    private javax.swing.JPanel jpnlDataIntegerEntry;
    private javax.swing.JPanel jpnlDataPersonEntry;
    private javax.swing.JPanel jpnlLista1;
    private javax.swing.JPanel jpnlLista2;
    private javax.swing.JPanel jpnlOperations;
    private javax.swing.JList<String> lstFinal;
    private javax.swing.JList<String> lstInitial;
    private javax.swing.JRadioButton rbtnAge;
    private javax.swing.JRadioButton rbtnName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtIntegerValue;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
